package gogll2

Grammar
    :   Sep Imports Sep Rules Sep
    ;

Imports
    :   Import Sep Imports
    |   emptyAlt
    ;

Import
    :   "import" String
    ;

Sep
    :   Spaces
    |   Spaces Sep
    |   Comment
    |   Comment Sep
    |   emptyAlt
    ;

Spaces
    :   space Spaces
    |   space
    ;

Comment
    :   "//" not "\n"
    ;

Rules
    :   Rule Sep Rules
    |   Rule
    |   emptyAlt
    ;

Rule
    :   Head Sep ":" Sep Alternatives
    ;

String
    :   '"' StringChars '"'
    ;

StringChar
    :   not "\""
    ;

StringChars 
    :   StringChar StringChars
    ;

Head
    :   upcase IdChars
    |   upcase
    ;

IdChars
    :   IdChar IdChars
    |   IdChar
    ;

IdChar
    :   letter
    |   number
    |   '_'
    ;

Alternatives
    :   Alternative Sep "|" Sep Alternatives
    |   Alternative
    ;

Alternative
    :   Body 
    |   emptyAlt
    ;

Body
    :   Symbol Sep Body
    |   Symbol
    ;

Symbol
    :   Head
    |   CharLiteral
    ;

CharLiteral
    :   '\'' not "'" '\''
    ;
