
// Package symbols is generated by gogll. Do not edit.
package symbols

type Symbol interface{
	isSymbol()
	IsNonTerminal() bool
	String() string
}

func (NT) isSymbol() {}
func (T) isSymbol() {}

// NT is the type of non-terminals symbols
type NT int
const( 
	NT_Expr NT = iota
	NT_Op 
)

// T is the type of terminals symbols
type T int
const( 
	T_0 T = iota // ERROR 
	T_1  // EOF 
	T_2  // & 
	T_3  // var 
	T_4  // | 
)

type Symbols []Symbol

func (ss Symbols) Strings() []string {
	strs := make([]string, len(ss))
	for i, s := range ss {
		strs[i] = s.String()
	}
	return strs
}

func (NT) IsNonTerminal() bool {
	return true
}

func (T) IsNonTerminal() bool {
	return false
}

func (nt NT) String() string {
	return ntToString[nt]
}

func (t T) String() string {
	return tToString[t]
}

var ntToString = []string { 
	"Expr", /* NT_Expr */
	"Op", /* NT_Op */ 
}

var tToString = []string { 
	"ERROR", /* T_0 */
	"EOF", /* T_1 */
	"&", /* T_2 */
	"var", /* T_3 */
	"|", /* T_4 */ 
}

var stringNT = map[string]NT{ 
	"Expr":NT_Expr,
	"Op":NT_Op,
}
