//! Generated by GoGLL. Do not edit.

use lazy_static::lazy_static;

lazy_static! { 
	pub static ref GOTO_TABLE: Vec<Vec<Option<usize>>> = {
		let m: Vec<Vec<Option<usize>>> = vec![
			vec![ // S0 
				Some(1), // Line 
				Some(2), // Lines 
			], 
			vec![ // S1 
				None, // Line 
				None, // Lines 
			], 
			vec![ // S2 
				Some(4), // Line 
				None, // Lines 
			], 
			vec![ // S3 
				None, // Line 
				None, // Lines 
			], 
			vec![ // S4 
				None, // Line 
				None, // Lines 
			], 
			vec![ // S5 
				None, // Line 
				None, // Lines 
			], 
			vec![ // S6 
				None, // Line 
				None, // Lines 
			], 
			vec![ // S7 
				None, // Line 
				None, // Lines 
			], 
			vec![ // S8 
				None, // Line 
				None, // Lines 
			], 
			vec![ // S9 
				None, // Line 
				None, // Lines 
			], 
			vec![ // S10 
				None, // Line 
				None, // Lines 
			], 
			vec![ // S11 
				None, // Line 
				None, // Lines 
			], 
			vec![ // S12 
				None, // Line 
				None, // Lines 
			], 
			vec![ // S13 
				None, // Line 
				None, // Lines 
			], 
		];
		m
	};
}
