//  Copyright 2019 Marius Ackerman
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.

package "gogll/test/gogll2"

Grammar
    :   Sep Imports Sep Rules Sep
    ;

Imports
    :   Import Sep Imports
    |   emptyAlt
    ;

Import
    :   "import" String
    ;

Sep
    :   Spaces
    |   Spaces Sep
    |   Comment
    |   Comment Sep
    |   emptyAlt
    ;

Spaces
    :   space Spaces
    |   space
    ;

Comment
    :   "//" not "\n"
    ;

Rules
    :   Rule Sep Rules
    |   Rule
    |   emptyAlt
    ;

Rule
    :   Head Sep ":" Sep Alternatives
    ;

String
    :   '"' StringChars '"'
    ;

StringChar
    :   not "\""
    ;

StringChars 
    :   StringChar StringChars
    ;

Head
    :   upcase IdChars
    |   upcase
    ;

IdChars
    :   IdChar IdChars
    |   IdChar
    ;

IdChar
    :   letter
    |   number
    |   '_'
    ;

Alternatives
    :   Alternative Sep "|" Sep Alternatives
    |   Alternative
    ;

Alternative
    :   Body 
    |   emptyAlt
    ;

Body
    :   Symbol Sep Body
    |   Symbol
    ;

Symbol
    :   Head
    |   CharLiteral
    ;

CharLiteral
    :   "'" not "'" "'"
    ;
