
/*
Generated by GoGLL. Do not edit
*/

package token

import(
    "fmt"
)

// Token is returned by the lexer for every scanned lexical token
type Token struct {
    Type Type
    Lext, Rext int
    Literal string
}

// Type is the token type
type Type = int
const(
    Error Type = iota
    EOF 
    Type0 // :
    Type1 // ;
    Type2 // empty
    Type3 // nt
    Type4 // package
    Type5 // string_lit
    Type6 // tokid
    Type7 // |
)

var TypeToString = []string{
    "Error",
    "EOF", 
    ":",
    ";",
    "empty",
    "nt",
    "package",
    "string_lit",
    "tokid",
    "|",
}

var StringToType = map[string] int {
    "Error": Error,
    "EOF": EOF, 
    ":": Type0,
    ";": Type1,
    "empty": Type2,
    "nt": Type3,
    "package": Type4,
    "string_lit": Type5,
    "tokid": Type6,
    "|": Type7,
}

func New(t Type, lext, rext int, lit []rune) *Token {
    return &Token{
        Type: t,
        Lext: lext,
        Rext: rext,
        Literal: string(lit),
    }
}

func (t *Token) String() string {
	return fmt.Sprintf("%s (%d,%d) %s",
		TypeToString[t.Type], t.Lext, t.Rext, t.Literal)
}
