// Code generated by gocc; DO NOT EDIT.

package parser

const numNTSymbols = 10

type (
	gotoTable [numStates]gotoRow
	gotoRow   [numNTSymbols]int
)

var gotoTab = gotoTable{
	gotoRow{ // S0
		-1, // S'
		1,  // Grammar
		2,  // Package
		3,  // Rules
		5,  // Rule
		6,  // Head
		-1, // Alternates
		-1, // Alternate
		-1, // Body
		-1, // Symbol
	},
	gotoRow{ // S1
		-1, // S'
		-1, // Grammar
		-1, // Package
		-1, // Rules
		-1, // Rule
		-1, // Head
		-1, // Alternates
		-1, // Alternate
		-1, // Body
		-1, // Symbol
	},
	gotoRow{ // S2
		-1, // S'
		-1, // Grammar
		-1, // Package
		8,  // Rules
		5,  // Rule
		6,  // Head
		-1, // Alternates
		-1, // Alternate
		-1, // Body
		-1, // Symbol
	},
	gotoRow{ // S3
		-1, // S'
		-1, // Grammar
		-1, // Package
		-1, // Rules
		9,  // Rule
		6,  // Head
		-1, // Alternates
		-1, // Alternate
		-1, // Body
		-1, // Symbol
	},
	gotoRow{ // S4
		-1, // S'
		-1, // Grammar
		-1, // Package
		-1, // Rules
		-1, // Rule
		-1, // Head
		-1, // Alternates
		-1, // Alternate
		-1, // Body
		-1, // Symbol
	},
	gotoRow{ // S5
		-1, // S'
		-1, // Grammar
		-1, // Package
		-1, // Rules
		-1, // Rule
		-1, // Head
		-1, // Alternates
		-1, // Alternate
		-1, // Body
		-1, // Symbol
	},
	gotoRow{ // S6
		-1, // S'
		-1, // Grammar
		-1, // Package
		-1, // Rules
		-1, // Rule
		-1, // Head
		-1, // Alternates
		-1, // Alternate
		-1, // Body
		-1, // Symbol
	},
	gotoRow{ // S7
		-1, // S'
		-1, // Grammar
		-1, // Package
		-1, // Rules
		-1, // Rule
		-1, // Head
		-1, // Alternates
		-1, // Alternate
		-1, // Body
		-1, // Symbol
	},
	gotoRow{ // S8
		-1, // S'
		-1, // Grammar
		-1, // Package
		-1, // Rules
		9,  // Rule
		6,  // Head
		-1, // Alternates
		-1, // Alternate
		-1, // Body
		-1, // Symbol
	},
	gotoRow{ // S9
		-1, // S'
		-1, // Grammar
		-1, // Package
		-1, // Rules
		-1, // Rule
		-1, // Head
		-1, // Alternates
		-1, // Alternate
		-1, // Body
		-1, // Symbol
	},
	gotoRow{ // S10
		-1, // S'
		-1, // Grammar
		-1, // Package
		-1, // Rules
		-1, // Rule
		-1, // Head
		-1, // Alternates
		-1, // Alternate
		-1, // Body
		-1, // Symbol
	},
	gotoRow{ // S11
		-1, // S'
		-1, // Grammar
		-1, // Package
		-1, // Rules
		-1, // Rule
		-1, // Head
		13, // Alternates
		15, // Alternate
		16, // Body
		18, // Symbol
	},
	gotoRow{ // S12
		-1, // S'
		-1, // Grammar
		-1, // Package
		-1, // Rules
		-1, // Rule
		-1, // Head
		-1, // Alternates
		-1, // Alternate
		-1, // Body
		-1, // Symbol
	},
	gotoRow{ // S13
		-1, // S'
		-1, // Grammar
		-1, // Package
		-1, // Rules
		-1, // Rule
		-1, // Head
		-1, // Alternates
		-1, // Alternate
		-1, // Body
		-1, // Symbol
	},
	gotoRow{ // S14
		-1, // S'
		-1, // Grammar
		-1, // Package
		-1, // Rules
		-1, // Rule
		-1, // Head
		-1, // Alternates
		-1, // Alternate
		-1, // Body
		-1, // Symbol
	},
	gotoRow{ // S15
		-1, // S'
		-1, // Grammar
		-1, // Package
		-1, // Rules
		-1, // Rule
		-1, // Head
		-1, // Alternates
		-1, // Alternate
		-1, // Body
		-1, // Symbol
	},
	gotoRow{ // S16
		-1, // S'
		-1, // Grammar
		-1, // Package
		-1, // Rules
		-1, // Rule
		-1, // Head
		-1, // Alternates
		-1, // Alternate
		-1, // Body
		29, // Symbol
	},
	gotoRow{ // S17
		-1, // S'
		-1, // Grammar
		-1, // Package
		-1, // Rules
		-1, // Rule
		-1, // Head
		-1, // Alternates
		-1, // Alternate
		-1, // Body
		-1, // Symbol
	},
	gotoRow{ // S18
		-1, // S'
		-1, // Grammar
		-1, // Package
		-1, // Rules
		-1, // Rule
		-1, // Head
		-1, // Alternates
		-1, // Alternate
		-1, // Body
		-1, // Symbol
	},
	gotoRow{ // S19
		-1, // S'
		-1, // Grammar
		-1, // Package
		-1, // Rules
		-1, // Rule
		-1, // Head
		-1, // Alternates
		-1, // Alternate
		-1, // Body
		-1, // Symbol
	},
	gotoRow{ // S20
		-1, // S'
		-1, // Grammar
		-1, // Package
		-1, // Rules
		-1, // Rule
		-1, // Head
		-1, // Alternates
		-1, // Alternate
		-1, // Body
		-1, // Symbol
	},
	gotoRow{ // S21
		-1, // S'
		-1, // Grammar
		-1, // Package
		-1, // Rules
		-1, // Rule
		-1, // Head
		-1, // Alternates
		-1, // Alternate
		-1, // Body
		-1, // Symbol
	},
	gotoRow{ // S22
		-1, // S'
		-1, // Grammar
		-1, // Package
		-1, // Rules
		-1, // Rule
		-1, // Head
		-1, // Alternates
		-1, // Alternate
		-1, // Body
		-1, // Symbol
	},
	gotoRow{ // S23
		-1, // S'
		-1, // Grammar
		-1, // Package
		-1, // Rules
		-1, // Rule
		-1, // Head
		-1, // Alternates
		-1, // Alternate
		-1, // Body
		-1, // Symbol
	},
	gotoRow{ // S24
		-1, // S'
		-1, // Grammar
		-1, // Package
		-1, // Rules
		-1, // Rule
		-1, // Head
		-1, // Alternates
		-1, // Alternate
		-1, // Body
		-1, // Symbol
	},
	gotoRow{ // S25
		-1, // S'
		-1, // Grammar
		-1, // Package
		-1, // Rules
		-1, // Rule
		-1, // Head
		-1, // Alternates
		-1, // Alternate
		-1, // Body
		-1, // Symbol
	},
	gotoRow{ // S26
		-1, // S'
		-1, // Grammar
		-1, // Package
		-1, // Rules
		-1, // Rule
		-1, // Head
		-1, // Alternates
		-1, // Alternate
		-1, // Body
		-1, // Symbol
	},
	gotoRow{ // S27
		-1, // S'
		-1, // Grammar
		-1, // Package
		-1, // Rules
		-1, // Rule
		-1, // Head
		-1, // Alternates
		-1, // Alternate
		-1, // Body
		-1, // Symbol
	},
	gotoRow{ // S28
		-1, // S'
		-1, // Grammar
		-1, // Package
		-1, // Rules
		-1, // Rule
		-1, // Head
		-1, // Alternates
		31, // Alternate
		16, // Body
		18, // Symbol
	},
	gotoRow{ // S29
		-1, // S'
		-1, // Grammar
		-1, // Package
		-1, // Rules
		-1, // Rule
		-1, // Head
		-1, // Alternates
		-1, // Alternate
		-1, // Body
		-1, // Symbol
	},
	gotoRow{ // S30
		-1, // S'
		-1, // Grammar
		-1, // Package
		-1, // Rules
		-1, // Rule
		-1, // Head
		-1, // Alternates
		-1, // Alternate
		-1, // Body
		-1, // Symbol
	},
	gotoRow{ // S31
		-1, // S'
		-1, // Grammar
		-1, // Package
		-1, // Rules
		-1, // Rule
		-1, // Head
		-1, // Alternates
		-1, // Alternate
		-1, // Body
		-1, // Symbol
	},
}
