
// Package symbols is generated by gogll. Do not edit.
package symbols

type Symbol interface{
	isSymbol()
	IsNonTerminal() bool
	String() string
}

func (NT) isSymbol() {}
func (T) isSymbol() {}

// NT is the type of non-terminals symbols
type NT int
const( 
	NT_A1 NT = iota
	NT_Name 
)

// T is the type of terminals symbols
type T int
const( 
	T_0 T = iota // int 
	T_1  // name 
)

type Symbols []Symbol

func (ss Symbols) Strings() []string {
	strs := make([]string, len(ss))
	for i, s := range ss {
		strs[i] = s.String()
	}
	return strs
}

func (NT) IsNonTerminal() bool {
	return true
}

func (T) IsNonTerminal() bool {
	return false
}

func (nt NT) String() string {
	return ntToString[nt]
}

func (t T) String() string {
	return tToString[t]
}

var ntToString = []string { 
	"A1", /* NT_A1 */
	"Name", /* NT_Name */ 
}

var tToString = []string { 
	"int", /* T_0 */
	"name", /* T_1 */ 
}

var stringNT = map[string]NT{ 
	"A1":NT_A1,
	"Name":NT_Name,
}
