// Code generated by gocc; DO NOT EDIT.

package parser

const numNTSymbols = 11

type (
	gotoTable [numStates]gotoRow
	gotoRow   [numNTSymbols]int
)

var gotoTab = gotoTable{
	gotoRow{ // S0
		-1, // S'
		1,  // GoGLL
		2,  // Package
		-1, // Rules
		-1, // Rule
		-1, // NT
		-1, // Alternates
		-1, // Alternate
		-1, // Symbols
		-1, // Symbol
		-1, // Terminal
	},
	gotoRow{ // S1
		-1, // S'
		-1, // GoGLL
		-1, // Package
		-1, // Rules
		-1, // Rule
		-1, // NT
		-1, // Alternates
		-1, // Alternate
		-1, // Symbols
		-1, // Symbol
		-1, // Terminal
	},
	gotoRow{ // S2
		-1, // S'
		-1, // GoGLL
		-1, // Package
		4,  // Rules
		5,  // Rule
		6,  // NT
		-1, // Alternates
		-1, // Alternate
		-1, // Symbols
		-1, // Symbol
		-1, // Terminal
	},
	gotoRow{ // S3
		-1, // S'
		-1, // GoGLL
		-1, // Package
		-1, // Rules
		-1, // Rule
		-1, // NT
		-1, // Alternates
		-1, // Alternate
		-1, // Symbols
		-1, // Symbol
		-1, // Terminal
	},
	gotoRow{ // S4
		-1, // S'
		-1, // GoGLL
		-1, // Package
		-1, // Rules
		9,  // Rule
		6,  // NT
		-1, // Alternates
		-1, // Alternate
		-1, // Symbols
		-1, // Symbol
		-1, // Terminal
	},
	gotoRow{ // S5
		-1, // S'
		-1, // GoGLL
		-1, // Package
		-1, // Rules
		-1, // Rule
		-1, // NT
		-1, // Alternates
		-1, // Alternate
		-1, // Symbols
		-1, // Symbol
		-1, // Terminal
	},
	gotoRow{ // S6
		-1, // S'
		-1, // GoGLL
		-1, // Package
		-1, // Rules
		-1, // Rule
		-1, // NT
		-1, // Alternates
		-1, // Alternate
		-1, // Symbols
		-1, // Symbol
		-1, // Terminal
	},
	gotoRow{ // S7
		-1, // S'
		-1, // GoGLL
		-1, // Package
		-1, // Rules
		-1, // Rule
		-1, // NT
		-1, // Alternates
		-1, // Alternate
		-1, // Symbols
		-1, // Symbol
		-1, // Terminal
	},
	gotoRow{ // S8
		-1, // S'
		-1, // GoGLL
		-1, // Package
		-1, // Rules
		-1, // Rule
		-1, // NT
		-1, // Alternates
		-1, // Alternate
		-1, // Symbols
		-1, // Symbol
		-1, // Terminal
	},
	gotoRow{ // S9
		-1, // S'
		-1, // GoGLL
		-1, // Package
		-1, // Rules
		-1, // Rule
		-1, // NT
		-1, // Alternates
		-1, // Alternate
		-1, // Symbols
		-1, // Symbol
		-1, // Terminal
	},
	gotoRow{ // S10
		-1, // S'
		-1, // GoGLL
		-1, // Package
		-1, // Rules
		-1, // Rule
		12, // NT
		13, // Alternates
		15, // Alternate
		16, // Symbols
		17, // Symbol
		18, // Terminal
	},
	gotoRow{ // S11
		-1, // S'
		-1, // GoGLL
		-1, // Package
		-1, // Rules
		-1, // Rule
		-1, // NT
		-1, // Alternates
		-1, // Alternate
		-1, // Symbols
		-1, // Symbol
		-1, // Terminal
	},
	gotoRow{ // S12
		-1, // S'
		-1, // GoGLL
		-1, // Package
		-1, // Rules
		-1, // Rule
		-1, // NT
		-1, // Alternates
		-1, // Alternate
		-1, // Symbols
		-1, // Symbol
		-1, // Terminal
	},
	gotoRow{ // S13
		-1, // S'
		-1, // GoGLL
		-1, // Package
		-1, // Rules
		-1, // Rule
		-1, // NT
		-1, // Alternates
		-1, // Alternate
		-1, // Symbols
		-1, // Symbol
		-1, // Terminal
	},
	gotoRow{ // S14
		-1, // S'
		-1, // GoGLL
		-1, // Package
		-1, // Rules
		-1, // Rule
		-1, // NT
		-1, // Alternates
		-1, // Alternate
		-1, // Symbols
		-1, // Symbol
		-1, // Terminal
	},
	gotoRow{ // S15
		-1, // S'
		-1, // GoGLL
		-1, // Package
		-1, // Rules
		-1, // Rule
		-1, // NT
		-1, // Alternates
		-1, // Alternate
		-1, // Symbols
		-1, // Symbol
		-1, // Terminal
	},
	gotoRow{ // S16
		-1, // S'
		-1, // GoGLL
		-1, // Package
		-1, // Rules
		-1, // Rule
		12, // NT
		-1, // Alternates
		-1, // Alternate
		-1, // Symbols
		22, // Symbol
		18, // Terminal
	},
	gotoRow{ // S17
		-1, // S'
		-1, // GoGLL
		-1, // Package
		-1, // Rules
		-1, // Rule
		-1, // NT
		-1, // Alternates
		-1, // Alternate
		-1, // Symbols
		-1, // Symbol
		-1, // Terminal
	},
	gotoRow{ // S18
		-1, // S'
		-1, // GoGLL
		-1, // Package
		-1, // Rules
		-1, // Rule
		-1, // NT
		-1, // Alternates
		-1, // Alternate
		-1, // Symbols
		-1, // Symbol
		-1, // Terminal
	},
	gotoRow{ // S19
		-1, // S'
		-1, // GoGLL
		-1, // Package
		-1, // Rules
		-1, // Rule
		-1, // NT
		-1, // Alternates
		-1, // Alternate
		-1, // Symbols
		-1, // Symbol
		-1, // Terminal
	},
	gotoRow{ // S20
		-1, // S'
		-1, // GoGLL
		-1, // Package
		-1, // Rules
		-1, // Rule
		-1, // NT
		-1, // Alternates
		-1, // Alternate
		-1, // Symbols
		-1, // Symbol
		-1, // Terminal
	},
	gotoRow{ // S21
		-1, // S'
		-1, // GoGLL
		-1, // Package
		-1, // Rules
		-1, // Rule
		12, // NT
		-1, // Alternates
		23, // Alternate
		16, // Symbols
		17, // Symbol
		18, // Terminal
	},
	gotoRow{ // S22
		-1, // S'
		-1, // GoGLL
		-1, // Package
		-1, // Rules
		-1, // Rule
		-1, // NT
		-1, // Alternates
		-1, // Alternate
		-1, // Symbols
		-1, // Symbol
		-1, // Terminal
	},
	gotoRow{ // S23
		-1, // S'
		-1, // GoGLL
		-1, // Package
		-1, // Rules
		-1, // Rule
		-1, // NT
		-1, // Alternates
		-1, // Alternate
		-1, // Symbols
		-1, // Symbol
		-1, // Terminal
	},
}
