//! Generated by GoGLL. Do not edit.

use lazy_static::lazy_static;

lazy_static! { 
	pub static ref GOTO_TABLE: Vec<Vec<Option<usize>>> = {
		let m: Vec<Vec<Option<usize>>> = vec![
			vec![ // S0 
				Some(1), // E1 
				Some(2), // T1 
			], 
			vec![ // S1 
				None, // E1 
				None, // T1 
			], 
			vec![ // S2 
				None, // E1 
				None, // T1 
			], 
			vec![ // S3 
				None, // E1 
				None, // T1 
			], 
			vec![ // S4 
				None, // E1 
				Some(5), // T1 
			], 
			vec![ // S5 
				None, // E1 
				None, // T1 
			], 
		];
		m
	};
}
