
// Package symbols is generated by gogll. Do not edit.
package symbols

type Symbol interface{
	isSymbol()
	IsNonTerminal() bool
	String() string
}

func (NT) isSymbol() {}
func (T) isSymbol() {}

// NT is the type of non-terminals symbols
type NT int
const( 
	NT_GoGLL NT = iota
	NT_LexAlternates 
	NT_LexBracket 
	NT_LexGroup 
	NT_LexOneOrMore 
	NT_LexOptional 
	NT_LexRule 
	NT_LexSymbol 
	NT_LexZeroOrMore 
	NT_Package 
	NT_RegExp 
	NT_Rule 
	NT_Rules 
	NT_SyntaxAlternate 
	NT_SyntaxAlternates 
	NT_SyntaxRule 
	NT_SyntaxSymbol 
	NT_SyntaxSymbols 
	NT_UnicodeClass 
)

// T is the type of terminals symbols
type T int
const( 
	T_0 T = iota // ERROR 
	T_1  // EOF 
	T_2  // ( 
	T_3  // ) 
	T_4  // . 
	T_5  // : 
	T_6  // ; 
	T_7  // < 
	T_8  // > 
	T_9  // [ 
	T_10  // ] 
	T_11  // any 
	T_12  // char_lit 
	T_13  // empty 
	T_14  // letter 
	T_15  // lowcase 
	T_16  // not 
	T_17  // nt 
	T_18  // number 
	T_19  // package 
	T_20  // string_lit 
	T_21  // tokid 
	T_22  // upcase 
	T_23  // { 
	T_24  // | 
	T_25  // } 
)

type Symbols []Symbol

func (ss Symbols) Strings() []string {
	strs := make([]string, len(ss))
	for i, s := range ss {
		strs[i] = s.String()
	}
	return strs
}

func (NT) IsNonTerminal() bool {
	return true
}

func (T) IsNonTerminal() bool {
	return false
}

func (nt NT) String() string {
	return ntToString[nt]
}

func (t T) String() string {
	return tToString[t]
}

var ntToString = []string { 
	"GoGLL", /* NT_GoGLL */
	"LexAlternates", /* NT_LexAlternates */
	"LexBracket", /* NT_LexBracket */
	"LexGroup", /* NT_LexGroup */
	"LexOneOrMore", /* NT_LexOneOrMore */
	"LexOptional", /* NT_LexOptional */
	"LexRule", /* NT_LexRule */
	"LexSymbol", /* NT_LexSymbol */
	"LexZeroOrMore", /* NT_LexZeroOrMore */
	"Package", /* NT_Package */
	"RegExp", /* NT_RegExp */
	"Rule", /* NT_Rule */
	"Rules", /* NT_Rules */
	"SyntaxAlternate", /* NT_SyntaxAlternate */
	"SyntaxAlternates", /* NT_SyntaxAlternates */
	"SyntaxRule", /* NT_SyntaxRule */
	"SyntaxSymbol", /* NT_SyntaxSymbol */
	"SyntaxSymbols", /* NT_SyntaxSymbols */
	"UnicodeClass", /* NT_UnicodeClass */ 
}

var tToString = []string { 
	"ERROR", /* T_0 */
	"EOF", /* T_1 */
	"(", /* T_2 */
	")", /* T_3 */
	".", /* T_4 */
	":", /* T_5 */
	";", /* T_6 */
	"<", /* T_7 */
	">", /* T_8 */
	"[", /* T_9 */
	"]", /* T_10 */
	"any", /* T_11 */
	"char_lit", /* T_12 */
	"empty", /* T_13 */
	"letter", /* T_14 */
	"lowcase", /* T_15 */
	"not", /* T_16 */
	"nt", /* T_17 */
	"number", /* T_18 */
	"package", /* T_19 */
	"string_lit", /* T_20 */
	"tokid", /* T_21 */
	"upcase", /* T_22 */
	"{", /* T_23 */
	"|", /* T_24 */
	"}", /* T_25 */ 
}

var stringNT = map[string]NT{ 
	"GoGLL":NT_GoGLL,
	"LexAlternates":NT_LexAlternates,
	"LexBracket":NT_LexBracket,
	"LexGroup":NT_LexGroup,
	"LexOneOrMore":NT_LexOneOrMore,
	"LexOptional":NT_LexOptional,
	"LexRule":NT_LexRule,
	"LexSymbol":NT_LexSymbol,
	"LexZeroOrMore":NT_LexZeroOrMore,
	"Package":NT_Package,
	"RegExp":NT_RegExp,
	"Rule":NT_Rule,
	"Rules":NT_Rules,
	"SyntaxAlternate":NT_SyntaxAlternate,
	"SyntaxAlternates":NT_SyntaxAlternates,
	"SyntaxRule":NT_SyntaxRule,
	"SyntaxSymbol":NT_SyntaxSymbol,
	"SyntaxSymbols":NT_SyntaxSymbols,
	"UnicodeClass":NT_UnicodeClass,
}
